### ISSUE TITLE
stock接口中的pyd文件在windows系统下不支持python3.10

### ISSUE THREAD

**Issue by CenturySee** [vnpy/vnpy_tora#17]
如题，win10系统下，pytho3.10单独安装vnpy_tora之后，新建gateway提示dll找不到的错误；切换至python3.7并安装对应包后可以正常连接至行情、交易服务器。可否向华鑫反馈下这个问题？

**Comment by vnpy** [comment]
之前我们反馈过，华鑫的回复是暂时没有提供Python 3.10的需求，建议以客户身份再向华鑫反馈下，可能人多了他们就会提供
