### ISSUE TITLE
tora期权接口部分撤单报错

### ISSUE THREAD

**Issue by andyxk3** [vnpy/vnpy_tora#18]
KeyError Traceback (most recent call last)
~\miniconda3\lib\site-packages\vnpy_tora\gateway\tora_option_gateway.py in OnRtnOrder(self, data)
531 volume=data["VolumeTotalOriginal"],
532 traded=data["VolumeTraded"],
--> 533 status=ORDER_STATUS_TORA2VT[bytes.decode(data["OrderStatus"])],
534 datetime=dt,
535 gateway_name=self.gateway_name

KeyError: '4'

以上为报错信息，此时为部分撤单状态。tora期权接口没有部分撤单代码。

![image](https://user-images.githubusercontent.com/42953389/221487503-ec43cfaa-4713-4ee6-86ee-8169be4762ee.png)

**Comment by vnpy** [comment]
需要升级华鑫奇点的接口API版本

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_tora/pull/22
