### ISSUE TITLE
仿真交易使用条件单录入请求时，提示找不到股东账户

### ISSUE THREAD

**Issue by liangmuxue** [vnpy/vnpy_tora#19]
仿真交易，ReqOrderInsert调用时，提示260找不到股东账户，可是在奇点网站的仿真交易说明中上没有看到相关股东账户设置，请问如何解决？

**Comment by vnpy** [comment]
ToraTdApi初始化时，会自动发起ReqQryShareholderAccount查询来获取股东账号，并在后续下单时传入。

如果出现260报错可能是这里的查询失败导致的，建议看下是否填错了用户账号。
